# Generated by Django 4.2.14 on 2024-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0005_grant_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveddemand",
            name="quantityplanned",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="planned quantity",
            ),
        ),
    ]
