# Generated by Django 4.2.14 on 2024-11-05 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="lastmodified",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="last modified",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="lastmodified",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="last modified",
            ),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="schedulingresource",
            name="lastmodified",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="last modified",
            ),
        ),
        migrations.AddField(
            model_name="schedulingresource",
            name="source",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=300,
                null=True,
                verbose_name="source",
            ),
        ),
    ]
