# Generated by Django 4.2.14 on 2024-11-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0002_schedulerconfiguration_lastmodified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulerconfiguration",
            name="lastmodified",
        ),
        migrations.RemoveField(
            model_name="schedulerconfiguration",
            name="source",
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="objective",
            field=models.CharField(
                choices=[
                    ("makespan", "Minimize makespan"),
                    ("tardiness", "Minimize tardiness"),
                    ("priority", "Priority based"),
                ],
                default="makespan",
                max_length=50,
                verbose_name="objective",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="time_limit",
            field=models.IntegerField(
                default=60,
                help_text="Maximum time allowed for solving",
                verbose_name="time limit (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="scheduling_method",
            field=models.CharField(
                choices=[("forward", "Forward"), ("backward", "Backward")],
                default="forward",
                max_length=50,
                verbose_name="scheduling method",
            ),
        ),
        migrations.AlterField(
            model_name="schedulingjob",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AlterModelTable(
            name="schedulerconfiguration",
            table=None,
        ),
    ]
