# Generated by Django 4.2.14 on 2024-11-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0076_alter_item_latedemandcount_and_more"),
        ("scheduler", "0003_remove_schedulerconfiguration_lastmodified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulingjob",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="schedulingjob",
            name="start_date",
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="demand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduling_jobs",
                to="input.demand",
                verbose_name="demand",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedulingjob",
            name="configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scheduler.schedulerconfiguration",
                verbose_name="configuration",
            ),
        ),
        migrations.AlterField(
            model_name="schedulingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterModelTable(
            name="schedulingjob",
            table=None,
        ),
    ]
