# Generated by Django 4.2.14 on 2024-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0004_remove_schedulingjob_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulingjob",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="start date"
            ),
        ),
    ]
