# Generated by Django 4.2.14 on 2024-11-06 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0077_alter_item_latedemandcount_and_more"),
        ("scheduler", "0005_schedulingjob_end_date_schedulingjob_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="batch_window",
            field=models.DurationField(
                blank=True,
                help_text="Time window for batching opportunities",
                null=True,
                verbose_name="batch window",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="consider_capacity",
            field=models.BooleanField(
                default=True,
                help_text="Whether to consider resource capacity in scheduling",
                verbose_name="consider capacity constraints",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="consider_material",
            field=models.BooleanField(
                default=True,
                help_text="Whether to consider material availability in scheduling",
                verbose_name="consider material constraints",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="fence_duration",
            field=models.DurationField(
                blank=True,
                help_text="Time window during which manufacturing orders are frozen",
                null=True,
                verbose_name="time fence",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="setup_matrix",
            field=models.ForeignKey(
                blank=True,
                help_text="Matrix defining setup times between operations",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="input.setupmatrix",
                verbose_name="setup matrix",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="size_minimum",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Minimum quantity for manufacturing orders",
                max_digits=20,
                null=True,
                verbose_name="minimum batch size",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="size_multiple",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Manufacturing order quantities must be a multiple of this size",
                max_digits=20,
                null=True,
                verbose_name="multiple batch size",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="wip_consume_capacity",
            field=models.BooleanField(
                default=True,
                help_text="Whether confirmed manufacturing orders consume capacity",
                verbose_name="WIP consume capacity",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="wip_consume_material",
            field=models.BooleanField(
                default=True,
                help_text="Whether confirmed manufacturing orders consume material",
                verbose_name="WIP consume material",
            ),
        ),
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="wip_produce_full_quantity",
            field=models.BooleanField(
                default=True,
                help_text="Whether WIP orders must produce their full quantity",
                verbose_name="WIP produce full quantity",
            ),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="buffer",
            field=models.ForeignKey(
                blank=True,
                help_text="Related buffer for material requirements",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="input.buffer",
                verbose_name="buffer",
            ),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item being produced or consumed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="input.item",
                verbose_name="item",
            ),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location where the operation is performed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="input.location",
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary resource required",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="input.resource",
                verbose_name="resource",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="scheduling_method",
            field=models.CharField(
                choices=[("forward", "Forward"), ("backward", "Backward")],
                default="backward",
                help_text="Forward: ASAP scheduling, Backward: JIT scheduling",
                max_length=50,
                verbose_name="scheduling method",
            ),
        ),
        migrations.AlterField(
            model_name="schedulingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=20, verbose_name="old status"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=20, verbose_name="new status"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="message"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="scheduler.schedulingjob",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingJobExecution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="start time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "solution_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="solution info"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scheduler.schedulingjob",
                        verbose_name="job",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
