# Generated by Django 4.2.14 on 2024-11-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0006_schedulerconfiguration_batch_window_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerconfiguration",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique identifier for URL",
                max_length=300,
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="horizon_end",
            field=models.DateTimeField(
                blank=True,
                help_text="End date and time of scheduling horizon (YYYY-MM-DD HH:mm:ss)",
                null=True,
                verbose_name="horizon end",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="horizon_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start date and time of scheduling horizon (YYYY-MM-DD HH:mm:ss)",
                null=True,
                verbose_name="horizon start",
            ),
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="time_limit",
            field=models.IntegerField(
                default=60,
                help_text="Time limit for the scheduler in seconds",
                verbose_name="time limit (seconds)",
            ),
        ),
    ]
