# Generated by Django 4.2.14 on 2024-11-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0007_schedulerconfiguration_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulerconfiguration",
            name="slug",
        ),
        migrations.AlterField(
            model_name="schedulerconfiguration",
            name="name",
            field=models.CharField(max_length=300, unique=True, verbose_name="name"),
        ),
    ]
