# Generated by Django 4.2.14 on 2024-11-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0008_remove_schedulerconfiguration_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulingjob",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="name"),
        ),
    ]
