# Generated by Django 4.2.14 on 2024-11-14 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0078_alter_item_latedemandcount_and_more"),
        ("scheduler", "0009_alter_schedulerconfiguration_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulingjob",
            name="operation",
        ),
        migrations.AddField(
            model_name="schedulingjob",
            name="operation_plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduling_jobs",
                to="input.operationplan",
                verbose_name="operation plan",
            ),
            preserve_default=False,
        ),
    ]
