# Generated by Django 4.2.14 on 2024-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportmanager", "0005_alter_model_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sqlreport",
            name="public",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
