# Generated by Django 4.2.14 on 2024-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecast", "0008_outliers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forecastplan",
            options={
                "managed": False,
                "ordering": ["id"],
                "verbose_name": "forecast plan",
                "verbose_name_plural": "forecast plans",
            },
        ),
        migrations.AlterField(
            model_name="forecast",
            name="batch",
            field=models.CharField(
                blank=True,
                help_text="MTO batch name",
                max_length=300,
                null=True,
                verbose_name="batch",
            ),
        ),
    ]
