# Generated by Django 4.2.14 on 2024-11-05 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("common", "0035_user_scenario_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_type_set_for_%(class)s",
                to="contenttypes.contenttype",
                verbose_name="content type",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="type",
            field=models.CharField(
                choices=[
                    ("add", "Add"),
                    ("change", "Change"),
                    ("delete", "Delete"),
                    ("comment", "comment"),
                    ("follower", "follower"),
                ],
                default="add",
                max_length=10,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="args",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="follower",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="model name",
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="object_pk",
            field=models.TextField(null=True, verbose_name="object name"),
        ),
        migrations.AlterField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="horizontype",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("auto", "Detect automatically"),
                    ("en", "English"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("he", "Hebrew"),
                    ("hr", "Croatian"),
                    ("it", "Italian"),
                    ("ja", "Japanese"),
                    ("nl", "Dutch"),
                    ("pt", "Portuguese"),
                    ("pt-br", "Brazilian Portuguese"),
                    ("ru", "Russian"),
                    ("es", "Spanish"),
                    ("zh-hans", "Simplified Chinese"),
                    ("zh-hant", "Traditional Chinese"),
                    ("uk", "Ukrainian"),
                ],
                default="en",
                max_length=10,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="value",
            field=models.JSONField(max_length=1000),
        ),
    ]
