# Generated by Django 4.2.14 on 2024-11-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0036_alter_comment_content_type_alter_comment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="model",
            field=models.CharField(
                choices=[
                    ("attribute", "attribute"),
                    ("bucket", "bucket"),
                    ("bucketdetail", "bucketdetail"),
                    ("buffer", "buffer"),
                    ("calendar", "calendar"),
                    ("calendarbucket", "calendarbucket"),
                    ("comment", "comment"),
                    ("customer", "customer"),
                    ("dataexport", "dataexport"),
                    ("demand", "demand"),
                    ("follower", "follower"),
                    ("forecast", "forecast"),
                    ("forecastplan", "forecastplan"),
                    ("forecastplanview", "forecastplanview"),
                    ("item", "item"),
                    ("itemdistribution", "itemdistribution"),
                    ("itemsupplier", "itemsupplier"),
                    ("location", "location"),
                    ("measure", "measure"),
                    ("notification", "notification"),
                    ("operation", "operation"),
                    ("operationdependency", "operationdependency"),
                    ("operationmaterial", "operationmaterial"),
                    ("operationplan", "operationplan"),
                    ("operationplanmaterial", "operationplanmaterial"),
                    ("operationplanresource", "operationplanresource"),
                    ("operationresource", "operationresource"),
                    ("parameter", "parameter"),
                    ("resource", "resource"),
                    ("resourceskill", "resourceskill"),
                    ("scenario", "scenario"),
                    ("scheduledtask", "scheduledtask"),
                    ("setupmatrix", "setupmatrix"),
                    ("setuprule", "setuprule"),
                    ("skill", "skill"),
                    ("suboperation", "suboperation"),
                    ("supplier", "supplier"),
                    ("systemmessage", "systemmessage"),
                    ("task", "task"),
                    ("user", "user"),
                    ("userpreference", "userpreference"),
                ],
                max_length=300,
                verbose_name="model",
            ),
        ),
    ]
