# Generated by Django 4.2.14 on 2024-11-05 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("input", "0074_buffer_maximum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationplan",
            options={
                "ordering": ["reference"],
                "verbose_name": "operationplan",
                "verbose_name_plural": "operationplans",
            },
        ),
        migrations.AlterModelOptions(
            name="operationplanmaterial",
            options={
                "ordering": ["item", "location", "flowdate"],
                "verbose_name": "inventory detail",
                "verbose_name_plural": "inventory detail",
            },
        ),
        migrations.AlterModelOptions(
            name="operationplanresource",
            options={
                "ordering": ["resource", "operationplan"],
                "verbose_name": "resource detail",
                "verbose_name_plural": "resource detail",
            },
        ),
        migrations.AlterField(
            model_name="buffer",
            name="batch",
            field=models.CharField(
                blank=True, default="", max_length=300, null=True, verbose_name="batch"
            ),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="friday",
            field=models.BooleanField(blank=True, default=True, verbose_name="Friday"),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="monday",
            field=models.BooleanField(blank=True, default=True, verbose_name="Monday"),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="saturday",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Saturday"
            ),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="startdate",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1971, 1, 1, 0, 0),
                null=True,
                verbose_name="start date",
            ),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="sunday",
            field=models.BooleanField(blank=True, default=True, verbose_name="Sunday"),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="thursday",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Thursday"
            ),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="tuesday",
            field=models.BooleanField(blank=True, default=True, verbose_name="Tuesday"),
        ),
        migrations.AlterField(
            model_name="calendarbucket",
            name="wednesday",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Wednesday"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="due",
            field=models.DateTimeField(
                db_index=True,
                help_text="Due date of the sales order",
                verbose_name="due",
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="plan",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="demand",
            name="quantity",
            field=models.DecimalField(
                decimal_places=8, max_digits=20, verbose_name="quantity"
            ),
        ),
        migrations.AlterField(
            model_name="demand",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("inquiry", "inquiry"),
                    ("quote", "quote"),
                    ("open", "open"),
                    ("closed", "closed"),
                    ("canceled", "canceled"),
                ],
                default="open",
                help_text='Status of the demand. Only "open" and "quote" demands are planned',
                max_length=10,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="adi",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="adi",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="cv2",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="cv2",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="demand_pattern",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=300,
                null=True,
                verbose_name="demand_pattern",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latedemandcount",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="count of late demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latedemandquantity",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="quantity of late demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latedemandvalue",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="value of late demand",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="outlier_12b",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="outliers last 12 buckets",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="outlier_1b",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="outliers last bucket",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="outlier_6b",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="outliers last 6 buckets",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="periodofcover",
            field=models.IntegerField(
                blank=True,
                editable=False,
                help_text="Period of cover in days",
                null=True,
                verbose_name="period of cover",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unplanneddemandcount",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="count of unplanned demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unplanneddemandquantity",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="quantity of unplanned demands",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="unplanneddemandvalue",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=6,
                editable=False,
                max_digits=15,
                null=True,
                verbose_name="value of unplanned demands",
            ),
        ),
        migrations.AlterField(
            model_name="itemdistribution",
            name="effective_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2030, 12, 31, 0, 0),
                help_text="Validity end date",
                null=True,
                verbose_name="effective end",
            ),
        ),
        migrations.AlterField(
            model_name="itemdistribution",
            name="effective_start",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1971, 1, 1, 0, 0),
                help_text="Validity start date",
                null=True,
                verbose_name="effective start",
            ),
        ),
        migrations.AlterField(
            model_name="itemdistribution",
            name="leadtime",
            field=models.DurationField(
                blank=True,
                help_text="Transport lead time",
                null=True,
                verbose_name="lead time",
            ),
        ),
        migrations.AlterField(
            model_name="itemdistribution",
            name="origin",
            field=models.ForeignKey(
                help_text="Source location shipping the item",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemdistributions_origin",
                to="input.location",
                verbose_name="origin",
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="effective_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2030, 12, 31, 0, 0),
                help_text="Validity end date",
                null=True,
                verbose_name="effective end",
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="effective_start",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1971, 1, 1, 0, 0),
                help_text="Validity start date",
                null=True,
                verbose_name="effective start",
            ),
        ),
        migrations.AlterField(
            model_name="itemsupplier",
            name="extra_safety_leadtime",
            field=models.DurationField(
                blank=True,
                help_text="soft safety lead time",
                null=True,
                verbose_name="soft safety lead time",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Cost per produced unit",
                max_digits=20,
                null=True,
                verbose_name="cost",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Fixed production time for setup and overhead",
                null=True,
                verbose_name="duration",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="duration_per",
            field=models.DurationField(
                blank=True,
                help_text="Production time per produced piece",
                null=True,
                verbose_name="duration per unit",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item produced by this operation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="input.item",
                verbose_name="item",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent operation (which must be of type routing, alternate or split)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="childoperations",
                to="input.operation",
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="sizemaximum",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Maximum production quantity",
                max_digits=20,
                null=True,
                verbose_name="size maximum",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="sizeminimum",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default="1.0",
                help_text="Minimum production quantity",
                max_digits=20,
                null=True,
                verbose_name="size minimum",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="sizemultiple",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Multiple production quantity",
                max_digits=20,
                null=True,
                verbose_name="size multiple",
            ),
        ),
        migrations.AlterField(
            model_name="operationdependency",
            name="blockedby",
            field=models.ForeignKey(
                help_text="blocked by operation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="input.operation",
                verbose_name="blocked by operation",
            ),
        ),
        migrations.AlterField(
            model_name="operationdependency",
            name="operation",
            field=models.ForeignKey(
                help_text="operation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies",
                to="input.operation",
                verbose_name="operation",
            ),
        ),
        migrations.AlterField(
            model_name="operationmaterial",
            name="effective_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2030, 12, 31, 0, 0),
                help_text="Validity end date",
                null=True,
                verbose_name="effective end",
            ),
        ),
        migrations.AlterField(
            model_name="operationmaterial",
            name="effective_start",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1971, 1, 1, 0, 0),
                help_text="Validity start date",
                null=True,
                verbose_name="effective start",
            ),
        ),
        migrations.AlterField(
            model_name="operationmaterial",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of this operation material to identify alternates",
                max_length=300,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="operationmaterial",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default="1.00",
                help_text="Quantity to consume or produce per piece",
                max_digits=20,
                null=True,
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="operationplan",
            name="forecast",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=300,
                null=True,
                verbose_name="forecast",
            ),
        ),
        migrations.AlterField(
            model_name="operationplan",
            name="plan",
            field=models.JSONField(blank=True, default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="operationplan",
            name="quantity_completed",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=20,
                null=True,
                verbose_name="completed quantity",
            ),
        ),
        migrations.AlterField(
            model_name="operationplan",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposed", "proposed"),
                    ("approved", "approved"),
                    ("confirmed", "confirmed"),
                    ("completed", "completed"),
                    ("closed", "closed"),
                ],
                help_text="Status of the order",
                max_length=20,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanmaterial",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="identifier"
            ),
        ),
        migrations.AlterField(
            model_name="operationplanmaterial",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operationplanmaterials",
                to="input.item",
                verbose_name="item",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanmaterial",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operationplanmaterials",
                to="input.location",
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanmaterial",
            name="operationplan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="input.operationplan",
                verbose_name="reference",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanmaterial",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposed", "proposed"),
                    ("confirmed", "confirmed"),
                    ("closed", "closed"),
                ],
                help_text="status of the material production or consumption",
                max_length=20,
                null=True,
                verbose_name="material status",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanresource",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="identifier"
            ),
        ),
        migrations.AlterField(
            model_name="operationplanresource",
            name="operationplan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="input.operationplan",
                verbose_name="reference",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanresource",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default=1.0,
                max_digits=20,
                null=True,
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="operationplanresource",
            name="setup",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="setup"
            ),
        ),
        migrations.AlterField(
            model_name="operationplanresource",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proposed", "proposed"),
                    ("confirmed", "confirmed"),
                    ("closed", "closed"),
                ],
                help_text="Status of the resource assignment",
                max_length=20,
                null=True,
                verbose_name="load status",
            ),
        ),
        migrations.AlterField(
            model_name="operationresource",
            name="effective_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2030, 12, 31, 0, 0),
                help_text="Validity end date",
                null=True,
                verbose_name="effective end",
            ),
        ),
        migrations.AlterField(
            model_name="operationresource",
            name="effective_start",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1971, 1, 1, 0, 0),
                help_text="Validity start date",
                null=True,
                verbose_name="effective start",
            ),
        ),
        migrations.AlterField(
            model_name="operationresource",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of this operation resource to identify alternates",
                max_length=300,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="operationresource",
            name="priority",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Priority of this operation resource in a group of alternates",
                null=True,
                verbose_name="priority",
            ),
        ),
        migrations.AlterField(
            model_name="operationresource",
            name="quantity_fixed",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Constant part of the capacity consumption (bucketized resources only)",
                max_digits=20,
                null=True,
                verbose_name="quantity fixed",
            ),
        ),
        migrations.AlterField(
            model_name="operationresource",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Required skill to perform the operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operationresources",
                to="input.skill",
                verbose_name="skill",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="constrained",
            field=models.BooleanField(
                blank=True,
                help_text="controls whether or not this resource is planned in finite capacity mode",
                null=True,
                verbose_name="constrained",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="overloadcount",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                editable=False,
                null=True,
                verbose_name="count of capacity overload problems",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="setupmatrix",
            field=models.ForeignKey(
                blank=True,
                help_text="Setup matrix defining the conversion time and cost",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="input.setupmatrix",
                verbose_name="setup matrix",
            ),
        ),
        migrations.AlterField(
            model_name="setuprule",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="identifier"
            ),
        ),
        migrations.AlterField(
            model_name="suboperation",
            name="effective_end",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2030, 12, 31, 0, 0),
                help_text="Validity end date",
                null=True,
                verbose_name="effective end",
            ),
        ),
        migrations.AlterField(
            model_name="suboperation",
            name="effective_start",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(1971, 1, 1, 0, 0),
                help_text="Validity start date",
                null=True,
                verbose_name="effective start",
            ),
        ),
    ]
